### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by m4rc1e** [wix/wixmadefor#13]
In order for us to push this family to Google Fonts, this repo must have a tagged release. The release must also have a zip file which contains the built fonts.

If you don't know how to do this, add me as a contributor to this repo and I'll do it.

**Comment by EgoziE** [comment]
I added you as a maintainer

**Comment by m4rc1e** [comment]
Thanks. I've just cut v1.200, https://github.com/wix/wixmadefor/releases/tag/1.200

I'll get these onboarded onto Google Fonts today. It may take a week or two for them to propagate through the pipeline though.
