### ISSUE TITLE
Update copyright notices in UFOs and rebuild

### ISSUE THREAD

**Issue by davelab6** [wix/wixmadefor#8]
Similar to https://github.com/wix/wixmadefor/pull/6 the copyright notices in the UFOs refer to a previous URL so should be updated. Eg

https://github.com/wix/wixmadefor/blob/b70d0d9b17a682c2f5f8a9bf55e55c1e3e8985a9/sources/WixMadeforText-Regular.ufo/fontinfo.plist#L10

**Comment by davelab6** [comment]
Possibly you didn't run https://github.com/wix/wixmadefor/blob/main/scripts/first-run.py

**Comment by EgoziE** [comment]
Fix github link
